#!/usr/bin/php
<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-02-07
 */
$path = __DIR__;
//delete
$command = 'rm -fr ' . $path . '/document/*';
passthru($command);

//generate
$options = array(
    '--source ' . $path . '/source/Net/Bazzline/Component/Command/',
    '--destination ' . $path . '/document/',
    '--title "Command by Bazzline"'
);
$command = 'php ' . $path . '/vendor/bin/apigen generate ' . implode(' ', $options);
passthru($command);
